// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx69XZ1nJxZ_sJnLsA08R3rKxkmrUcqBE',
    appId: '1:546497743604:web:9259b2ff2952e9c7ececa1',
    messagingSenderId: '546497743604',
    projectId: 'food-delivery-c47ca',
    authDomain: 'food-delivery-c47ca.firebaseapp.com',
    storageBucket: 'food-delivery-c47ca.appspot.com',
    measurementId: 'G-RXKN9CX7H7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo99TiCIXuDWvv01BxovwvkO2SJRL-l54',
    appId: '1:546497743604:android:f70825c2d26451c1ececa1',
    messagingSenderId: '546497743604',
    projectId: 'food-delivery-c47ca',
    storageBucket: 'food-delivery-c47ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWKC1TnxtRxhtn9IWszJBOrwiGMtHBgbQ',
    appId: '1:546497743604:ios:17fdde97de28bff0ececa1',
    messagingSenderId: '546497743604',
    projectId: 'food-delivery-c47ca',
    storageBucket: 'food-delivery-c47ca.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );
}
